#.travis.yml

language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
  - npm install

script:
  - ng build --prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive
  - curl --ftp-create-dirs -T dist/favicon.ico -u $FTP_USER:$FTP_PASSWORD ftp://spotground.com

notifications:
  email:
    on_failure: change
    on_success: change
